apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: 7days-build-game
  labels:
    application: okd-7daystodie  
spec:
  source:
    git:
      ref: dev
      uri: 'https://github.com/Cardes/steamcmd.git'
    contextDir: gameimages/7daystodie
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      from:
        kind: "ImageStreamTag"
        name: "okd-steamcmd:latest"
    triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  output:
    to:
      kind: ImageStreamTag
      name: okd-7daystodie:latest
