FROM ubuntu:22.04
ENV SERVERNAME 'Valheim Dedicated Server for OKD'
#Gameserver uses the range from 'serverport' to 'serverport'+2
ENV SERVERPORT 2456
ENV WORLDNAME 'Dedicated'
ENV SERVERPASSWORD 'YouShouldChangeThis'
ENV SAVEPATH "/mygame/saves"
VOLUME [ "/mygame/gamefiles" ,"/mygame/saves" ]
WORKDIR /mygame
COPY --chmod=555 src/entrypoint.sh /mygame
RUN mkdir -p ${SAVEPATH} \
    && chgrp -R 0 ${SAVEPATH} \
    && chmod -R g=u ${SAVEPATH}
ENTRYPOINT [ "/mygame/./entrypoint.sh" ]

 