FROM ubuntu:22.04
ENV SERVERNAME 'Valheim Dedicated Server for OKD'
#Gameserver uses the range from 'serverport' to 'serverport'+2
ENV SERVERPORT 2456
ENV WORLDNAME 'Dedicated'
ENV SERVERPASSWORD 'YouShouldChangeThis'
VOLUME [ "/mygame/gamefiles" ]
COPY --chmod=555 src/entrypoint.sh /mygame
WORKDIR /mygame
ENTRYPOINT [ "/mygame/./entrypoint.sh" ]

 