FROM docker.io/steamcmd/steamcmd:ubuntu-20
#overwrite ENV for our user
ENV HOME /mygame/gamefiles
#source dedicated as default
ENV APPNUMBER 205 
#allow the group to write and execute, this can't be bound to a specifc ID as openshift assigns random ids
RUN mkdir -p /mygame/gamefiles \
    && chgrp -R 0 /mygame \
    && chmod -R g=u /mygame \
    && chgrp -R 0 /tmp \
    && chmod -R g=u /tmp
VOLUME ["/mygame/gamefiles"]
WORKDIR /mygame
COPY --chmod=555 src/entrypoint.sh /mygame
ENTRYPOINT [ "/mygame/./entrypoint.sh" ]
