apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: okd-steamcmd-build
  labels:
    application: okd-steamcmd
spec:
  source:
    git:
      ref: dev
      uri: 'https://github.com/Cardes/steamcmd.git'
    contextDir: baseimage
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'okd-steamcmd:latest'
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
